### ISSUE TITLE
How i can use the styles generated in my custom componentes?

### ISSUE THREAD

**Issue by Miguerfi** [jln13x/ui.jln.dev#12]
i'm trayna use the colors in my componenets but don't know how i do it.

**Comment by jln13x** [comment]
Which styles are you talking about?
Are you using shadcn/ui in your project?

**Comment by Miguerfi** [comment]
just found a way. and i'ma talking about these for example:
![image](https://github.com/jln13x/ui.jln.dev/assets/91486755/3cbbd5c4-eb32-40d4-9568-b8728759707b)

i'ma using like this in the code:
![image](https://github.com/jln13x/ui.jln.dev/assets/91486755/cf8c3700-8331-43d7-bf85-3a3ee69c599b)

and yes i'm using shadcn components but i have build my own components.

**Comment by jln13x** [comment]
yes exactly just use the variables 🙌
enjoy man

**Comment by Miguerfi** [comment]
thx
