### ISSUE TITLE
Previous Button pops elements in the wrong order

### ISSUE THREAD

**Issue by robinsmith-source** [jln13x/ui.jln.dev#15]
I've found the issue, which is that the previous button pops the themes in a Last In, First Out (LIFO) pattern. When more than 2 themes are on the stack and the previous button is pressed, they are applied in reverse order. Thus, the most recently added theme becomes the very last one to be applied.

**Comment by immiProgrammer** [comment]
agree

**Comment by immiProgrammer** [comment]
[fix this problem use this hook](https://github.com/WebDevSimplified/useful-custom-react-hooks/tree/main/src/7-useStateWithHistory)

**Comment by jln13x** [comment]
should be fixed thanks
