### ISSUE TITLE
Repo license is missing

### ISSUE THREAD

**Issue by shmuelhizmi** [jln13x/ui.jln.dev#24]
Hey Hey, really cool and useful project, thanks for creating it :)

I would like to use some of the code in here, if can you declare a repo license it would be awesome

**Comment by jln13x** [comment]
feel free to use it, i dont mind

**Comment by xbc5** [comment]
Please just add a license lol.

"Yes your honor.. he said: 'trust me bro'".

MIT is a decent choice, or CC-BY-SA.

**Comment by jln13x** [comment]
done
