### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by ParzivalFR** [jln13x/ui.jln.dev#29]
Your site is down, the link is `Null`
![Screenshot_1](https://github.com/user-attachments/assets/1aeaba4e-28a8-4667-a0be-19b92012467c)

**Comment by jln13x** [comment]
thanks for letting me know, seems to be up for me again.
can you check @ParzivalFR please? :)

**Comment by jln13x** [comment]
> If it suits you I will put your site on https://kitilib.com, is it good for you? 🙂

would be awesome, thanks alot 🔥
